  name: 'Hello World'
  description: 'Greet someone'
  inputs:
    azure-context:  # id of input
      description: 'Who to greet'
      required: true
  outputs:
    aks-cluster :
      value: ${{ steps.aks-context.outputs.aks-cluster }}
  runs:
    using: "composite"
    steps:
      - run: echo "${{ fromJSON(inputs.azure-context).aks-cluster }}"
        shell: bash
      - id: aks-context
        run: echo "value=$(echo '${{ inputs.azure-context }}' | jq -r '.aks-cluster') >> $GITHUB_OUTPUT
        shell: bash

