  name: 'Hello World'
  description: 'Greet someone'
  inputs:
    cluster-config:  # id of input
      description: 'Who to greet'
      required: true
  outputs:
    aks-name:
      value: ${{ steps.random-number-generator.outputs.aks-name }}
  runs:
    using: "composite"
    steps:
      - id: aks-context
        run: echo "aks-name=$(echo ${{ fromJSON(inputs.cluster-config.aks-name)}})" >> $GITHUB_OUTPUT
        shell: bash

