  name: 'Hello World'
  description: 'Greet someone'
  inputs:
    azure-context:  # id of input
      description: 'Who to greet'
      required: true
  outputs:
    aks-cluster :
      value: ${{ steps.aks-context.outputs.aks-cluster }}
  runs:
    using: "composite"
    steps:
      - id: aks-context
        run: echo "aks-cluster=$(echo '${{ inputs.azure-context }}' | jq -r '.aksCluster')" >> $GITHUB_OUTPUT
        shell: bash

