  name: 'Hello World'
  description: 'Greet someone'
  inputs:
    azure-context:  # id of input
      description: 'Who to greet'
      required: true
  outputs:
    aks-cluster :
      value: ${{ steps.random-number-generator.outputs.aks-cluster }}
  runs:
    using: "composite"
    steps:
      - id: aks-context
        run: echo "aks-name=${{ fromJSON(inputs.azure-context.aks-cluster) }}" >> $GITHUB_OUTPUT
        shell: bash

