on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./.github/actions/my-action
        with:
          azure-context: ${{ vars.AZURE_CONTEXT }}
      - run: echo aksname ${{ steps.foo.outputs.aks-name }}
        shell: bash
